# Generated by Django 3.1.6 on 2021-02-14 15:21

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20210207_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Image',
            field=models.ImageField(default='', upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
