# Generated by Django 3.1.6 on 2021-02-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
