# Generated by Django 3.1.6 on 2021-02-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210220_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apply',
        ),
    ]
