# Generated by Django 3.1.6 on 2021-02-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='website',
            new_name='web_site',
        ),
    ]
